/*
 * Kjarni FFI - C bindings for Kjarni ML library
 * Auto-generated by cbindgen. Do not edit manually.
 */


#ifndef KJARNI_FFI_H
#define KJARNI_FFI_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Error codes returned by Kjarni FFI functions.
 */
typedef enum KjarniErrorCode {
  /**
   * Operation completed successfully
   */
  KJARNI_ERROR_CODE_OK = 0,
  /**
   * Null pointer passed to function
   */
  KJARNI_ERROR_CODE_NULL_POINTER = 1,
  /**
   * Invalid UTF-8 string
   */
  KJARNI_ERROR_CODE_INVALID_UTF8 = 2,
  /**
   * Model not found in registry
   */
  KJARNI_ERROR_CODE_MODEL_NOT_FOUND = 3,
  /**
   * Failed to load model
   */
  KJARNI_ERROR_CODE_LOAD_FAILED = 4,
  /**
   * Inference operation failed
   */
  KJARNI_ERROR_CODE_INFERENCE_FAILED = 5,
  /**
   * GPU not available
   */
  KJARNI_ERROR_CODE_GPU_UNAVAILABLE = 6,
  /**
   * Invalid configuration
   */
  KJARNI_ERROR_CODE_INVALID_CONFIG = 7,
  /**
   * Operation was cancelled
   */
  KJARNI_ERROR_CODE_CANCELLED = 8,
  /**
   * Operation timed out
   */
  KJARNI_ERROR_CODE_TIMEOUT = 9,
  /**
   * Stream has ended
   */
  KJARNI_ERROR_CODE_STREAM_ENDED = 10,
  /**
   * A panic in the engine was caught at the ABI boundary. The library is in an
   * unspecified state for the operation that failed; the handle itself remains
   * valid to free. `kjarni_last_error_message` names the entry point.
   */
  KJARNI_ERROR_CODE_PANIC = 11,
  /**
   * Unknown error
   */
  KJARNI_ERROR_CODE_UNKNOWN = 255,
} KjarniErrorCode;

/**
 * Device selection for inference.
 */
typedef enum KjarniDevice {
  /**
   * Use CPU for inference
   */
  KJARNI_DEVICE_CPU = 0,
  /**
   * Use GPU for inference
   */
  KJARNI_DEVICE_GPU = 1,
} KjarniDevice;

/**
 * Progress stage enum for FFI
 */
typedef enum KjarniProgressStage {
  KJARNI_PROGRESS_STAGE_SCANNING = 0,
  KJARNI_PROGRESS_STAGE_LOADING = 1,
  KJARNI_PROGRESS_STAGE_EMBEDDING = 2,
  KJARNI_PROGRESS_STAGE_WRITING = 3,
  KJARNI_PROGRESS_STAGE_COMMITTING = 4,
  KJARNI_PROGRESS_STAGE_SEARCHING = 5,
  KJARNI_PROGRESS_STAGE_RERANKING = 6,
} KjarniProgressStage;

typedef enum KjarniSearchMode {
  KJARNI_SEARCH_MODE_KEYWORD = 0,
  KJARNI_SEARCH_MODE_SEMANTIC = 1,
  KJARNI_SEARCH_MODE_HYBRID = 2,
} KjarniSearchMode;

/**
 * Cancellation token
 */
typedef struct KjarniCancelToken KjarniCancelToken;

/**
 * Opaque handle to a Chat instance.
 */
typedef struct KjarniChat KjarniChat;

/**
 * Opaque handle to a stateful ChatConversation.
 *
 * Owns the history and holds a raw pointer back to the parent Chat.
 * The parent Chat must outlive this handle.
 */
typedef struct KjarniChatConversation KjarniChatConversation;

/**
 * Opaque handle to a Classifier.
 */
typedef struct KjarniClassifier KjarniClassifier;

/**
 * Opaque handle to an Embedder instance.
 */
typedef struct KjarniEmbedder KjarniEmbedder;

/**
 * Opaque handle to an Indexer instance.
 *
 * Created via `kjarni_indexer_new`, must be freed via `kjarni_indexer_free`
 */
typedef struct KjarniIndexer KjarniIndexer;

/**
 * Opaque handle to a Reranker
 */
typedef struct KjarniReranker KjarniReranker;

typedef struct KjarniSearcher KjarniSearcher;

/**
 * Float array returned by FFI functions. Caller must free with kjarni_float_array_free.
 */
typedef struct KjarniFloatArray {
  float *data;
  uintptr_t len;
} KjarniFloatArray;

/**
 * 2D float array for batch results. Caller must free with kjarni_float_2d_array_free.
 */
typedef struct KjarniFloat2DArray {
  float *data;
  uintptr_t rows;
  uintptr_t cols;
} KjarniFloat2DArray;

/**
 * String array. Caller must free with kjarni_string_array_free.
 */
typedef struct KjarniStringArray {
  char **strings;
  uintptr_t len;
} KjarniStringArray;

/**
 * Configuration for creating a Chat instance.
 */
typedef struct KjarniChatConfig {
  /**
   * Device to use (0 = CPU, 1 = GPU)
   */
  enum KjarniDevice device;
  /**
   * Cache directory (NULL = default)
   */
  const char *cache_dir;
  /**
   * Model name (required) - e.g. "llama3.2-1b-instruct"
   */
  const char *model_name;
  /**
   * Model path (NULL = use registry)
   */
  const char *model_path;
  /**
   * System prompt (NULL = use model default)
   */
  const char *system_prompt;
  /**
   * Chat mode: 0 = default, 1 = creative, 2 = reasoning
   */
  int32_t mode;
  /**
   * Suppress output
   */
  int32_t quiet;
} KjarniChatConfig;

/**
 * Generation parameters. Use -1 sentinel values to keep model defaults.
 */
typedef struct KjarniGenerationConfig {
  /**
   * Sampling temperature. -1.0 = use default.
   */
  float temperature;
  /**
   * Top-k sampling. -1 = use default.
   */
  int32_t top_k;
  /**
   * Top-p (nucleus) sampling. -1.0 = use default.
   */
  float top_p;
  /**
   * Min-p sampling threshold. -1.0 = use default.
   */
  float min_p;
  /**
   * Repetition penalty. -1.0 = use default.
   */
  float repetition_penalty;
  /**
   * Max new tokens to generate. -1 = use default.
   */
  int32_t max_new_tokens;
  /**
   * Sampling mode. -1 = default, 0 = greedy, 1 = sample.
   */
  int32_t do_sample;
} KjarniGenerationConfig;

/**
 * Token callback for streaming. Return false to stop generation.
 */
typedef bool (*KjarniStreamCallbackFn)(const char *text, void *user_data);

/**
 * Single classification result (label + score).
 */
typedef struct KjarniClassResult {
  char *label;
  float score;
} KjarniClassResult;

typedef struct KjarniClassResults {
  struct KjarniClassResult *results;
  uintptr_t len;
} KjarniClassResults;

typedef struct KjarniClassifierConfig {
  /**
   * Device to use
   */
  enum KjarniDevice device;
  /**
   * Cache directory (NULL = default)
   */
  const char *cache_dir;
  /**
   * Model name (NULL = default)
   */
  const char *model_name;
  /**
   * Model path (NULL = use registry)
   */
  const char *model_path;
  /**
   * Custom labels (NULL = use model labels)
   */
  const char *const *labels;
  /**
   * Number of custom labels
   */
  uintptr_t num_labels;
  /**
   * Multi-label mode (1 = multi-label, 0 = single-label)
   */
  int32_t multi_label;
  /**
   * Suppress output
   */
  int32_t quiet;
} KjarniClassifierConfig;

/**
 * Configuration for creating an Embedder.
 */
typedef struct KjarniEmbedderConfig {
  /**
   * Device to use (CPU or GPU)
   */
  enum KjarniDevice device;
  /**
   * Cache directory for models (NULL = default)
   */
  const char *cache_dir;
  /**
   * Model name from registry (NULL = "minilm-l6-v2")
   */
  const char *model_name;
  /**
   * Path to local model (NULL = use registry)
   */
  const char *model_path;
  /**
   * Whether to L2-normalize embeddings (1 = yes, 0 = no)
   */
  int32_t normalize;
  /**
   * Suppress progress output (1 = quiet, 0 = verbose)
   */
  int32_t quiet;
} KjarniEmbedderConfig;

/**
 * Information about an existing index
 */
typedef struct KjarniIndexInfo {
  /**
   * Path to the index directory (must be freed)
   */
  char *path;
  /**
   * Total number of documents in the index
   */
  uintptr_t document_count;
  /**
   * Number of index segments
   */
  uintptr_t segment_count;
  /**
   * Embedding dimension
   */
  uintptr_t dimension;
  /**
   * Total size on disk in bytes
   */
  uint64_t size_bytes;
  /**
   * Embedding model name used to create the index (may be NULL, must be freed if not)
   */
  char *embedding_model;
} KjarniIndexInfo;

/**
 * Configuration for creating an Indexer
 */
typedef struct KjarniIndexerConfig {
  /**
   * Device to run embeddings on (CPU or GPU)
   */
  enum KjarniDevice device;
  /**
   * Directory to cache downloaded models (NULL = system default)
   */
  const char *cache_dir;
  /**
   * Embedding model name (NULL = "minilm-l6-v2")
   */
  const char *model_name;
  /**
   * Maximum chunk size in characters
   */
  uintptr_t chunk_size;
  /**
   * Overlap between adjacent chunks in characters
   */
  uintptr_t chunk_overlap;
  /**
   * Batch size for embedding operations
   */
  uintptr_t batch_size;
  /**
   * Comma-separated list of file extensions to include (NULL = use defaults)
   */
  const char *extensions;
  /**
   * Comma-separated list of glob patterns to exclude
   */
  const char *exclude_patterns;
  /**
   * Whether to recurse into subdirectories (1 = true, 0 = false)
   */
  int32_t recursive;
  /**
   * Whether to include hidden files (1 = true, 0 = false)
   */
  int32_t include_hidden;
  /**
   * Maximum file size in bytes (0 = no limit)
   */
  uintptr_t max_file_size;
  /**
   * Suppress progress output to stderr (1 = quiet, 0 = verbose)
   */
  int32_t quiet;
} KjarniIndexerConfig;

typedef struct KjarniIndexStats {
  /**
   * Number of document chunks indexed (after splitting)
   */
  uintptr_t documents_indexed;
  /**
   * Number of chunks created from source files
   */
  uintptr_t chunks_created;
  /**
   * Embedding dimension used
   */
  uintptr_t dimension;
  /**
   * Total index size on disk in bytes
   */
  uint64_t size_bytes;
  /**
   * Number of source files successfully processed
   */
  uintptr_t files_processed;
  /**
   * Number of source files skipped (errors, unsupported format, too large)
   */
  uintptr_t files_skipped;
  /**
   * Total time taken in milliseconds
   */
  uint64_t elapsed_ms;
} KjarniIndexStats;

/**
 * Progress data passed to callbacks
 */
typedef struct KjarniProgress {
  enum KjarniProgressStage stage;
  uintptr_t current;
  uintptr_t total;
  const char *message;
} KjarniProgress;

/**
 * Generic callback function pointer type for progress
 */
typedef void (*KjarniProgressCallbackFn)(struct KjarniProgress progress, void *user_data);

/**
 * Single rerank result
 */
typedef struct KjarniRerankResult {
  uintptr_t index;
  float score;
} KjarniRerankResult;

/**
 * Array of rerank results
 */
typedef struct KjarniRerankResults {
  struct KjarniRerankResult *results;
  uintptr_t len;
} KjarniRerankResults;

/**
 * Configuration for Reranker
 */
typedef struct KjarniRerankerConfig {
  enum KjarniDevice device;
  const char *cache_dir;
  const char *model_name;
  const char *model_path;
  int32_t quiet;
} KjarniRerankerConfig;

typedef struct KjarniSearchResult {
  float score;
  uintptr_t document_id;
  char *text;
  char *metadata_json;
} KjarniSearchResult;

typedef struct KjarniSearchResults {
  struct KjarniSearchResult *results;
  uintptr_t len;
} KjarniSearchResults;

typedef struct KjarniSearchOptions {
  int32_t mode;
  uintptr_t top_k;
  int32_t use_reranker;
  float threshold;
  const char *source_pattern;
  const char *filter_key;
  const char *filter_value;
} KjarniSearchOptions;

typedef struct KjarniSearcherConfig {
  enum KjarniDevice device;
  const char *cache_dir;
  const char *model_name;
  const char *rerank_model;
  enum KjarniSearchMode default_mode;
  uintptr_t default_top_k;
  int32_t quiet;
} KjarniSearcherConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the Kjarni runtime. Optional - auto-initialized on first use.
 */
enum KjarniErrorCode kjarni_init(void);

/**
 * Shutdown and cleanup. Call before process exit.
 */
void kjarni_shutdown(void);

/**
 * Get the library version string.
 */
const char *kjarni_version(void);

/**
 * Free a float array allocated by Kjarni.
 *
 * # Safety
 *
 * - `arr` must be a value returned by a search/embedding call, passed here exactly once. Its
 *   buffers are invalid to read afterwards.
 */
void kjarni_float_array_free(struct KjarniFloatArray arr);

/**
 * Free a 2D float array allocated by Kjarni.
 *
 * # Safety
 *
 * - `arr` must be a value returned by `kjarni_embedder_encode_batch`, passed here exactly once.
 *   Its buffers are invalid to read afterwards.
 */
void kjarni_float_2d_array_free(struct KjarniFloat2DArray arr);

/**
 * Free a string allocated by Kjarni.
 *
 * # Safety
 *
 * - `s` must be a valid, writable pointer to a `std::ffi::c_char`. It is written on both
 *   success and failure, and any buffers it receives are owned by the caller.
 */
void kjarni_string_free(char *s);

/**
 * Free a string array allocated by Kjarni.
 *
 * # Safety
 *
 * - `arr` must be a value returned by a call that returns one, passed here exactly once. Its
 *   buffers are invalid to read afterwards.
 */
void kjarni_string_array_free(struct KjarniStringArray arr);

/**
 * # Safety
 *
 * - `a` must be null, or point to at least `len` readable `f32` values.
 * - `b` must be null, or point to at least `len` readable `f32` values.
 */
float kjarni_cosine_similarity(const float *a, const float *b, uintptr_t len);

struct KjarniCancelToken *kjarni_cancel_token_new(void);

/**
 * # Safety
 *
 * - `token` must be null, or a live handle returned by `kjarni_cancel_token_new` that has not
 *   been freed.
 */
void kjarni_cancel_token_cancel(struct KjarniCancelToken *token);

/**
 * # Safety
 *
 * - `token` must be null, or a live handle returned by `kjarni_cancel_token_new` that has not
 *   been freed.
 */
bool kjarni_cancel_token_is_cancelled(const struct KjarniCancelToken *token);

/**
 * # Safety
 *
 * - `token` must be null, or a live handle returned by `kjarni_cancel_token_new` that has not
 *   been freed.
 */
void kjarni_cancel_token_reset(struct KjarniCancelToken *token);

/**
 * # Safety
 *
 * - `token` must be null, or a handle returned by `kjarni_cancel_token_new` that has not
 *   already been passed to this function. It is invalid to use afterwards.
 */
void kjarni_cancel_token_free(struct KjarniCancelToken *token);

/**
 * Get default chat configuration.
 */
struct KjarniChatConfig kjarni_chat_config_default(void);

/**
 * Get default generation configuration (all sentinels = use model defaults).
 */
struct KjarniGenerationConfig kjarni_generation_config_default(void);

/**
 * Create a new Chat instance.
 *
 * # Safety
 * - `config` must be valid or NULL (uses defaults)
 * - `out` must be a valid pointer
 * - The returned handle must be freed with `kjarni_chat_free`
 */
enum KjarniErrorCode kjarni_chat_new(const struct KjarniChatConfig *config,
                                     struct KjarniChat **out);

/**
 * Free a Chat instance.
 */
void kjarni_chat_free(struct KjarniChat *chat);

/**
 * Send a message and get the full response.
 *
 * # Safety
 * - `chat` must be a valid handle from `kjarni_chat_new`
 * - `message` must be a valid UTF-8 C string
 * - `gen_config` may be NULL (uses defaults)
 * - `out` must be a valid pointer; caller must free result with `kjarni_string_free`
 */
enum KjarniErrorCode kjarni_chat_send(struct KjarniChat *chat,
                                      const char *message,
                                      const struct KjarniGenerationConfig *gen_config,
                                      char **out);

/**
 * Stream a response token by token via callback.
 *
 * The callback receives each token's text as a C string. Return `false`
 * from the callback to stop generation early.
 *
 * # Safety
 * - `chat` must be a valid handle
 * - `message` must be valid UTF-8
 * - `callback` must be a valid function pointer
 * - `cancel_token` may be NULL
 */
enum KjarniErrorCode kjarni_chat_stream(struct KjarniChat *chat,
                                        const char *message,
                                        const struct KjarniGenerationConfig *gen_config,
                                        KjarniStreamCallbackFn callback,
                                        void *user_data,
                                        const struct KjarniCancelToken *cancel_token);

/**
 * Send a message with explicit history. Does not modify the history
 */
enum KjarniErrorCode kjarni_chat_send_with_history(struct KjarniChat *chat,
                                                   const int32_t *roles,
                                                   const char *const *contents,
                                                   uintptr_t history_len,
                                                   const char *message,
                                                   const struct KjarniGenerationConfig *gen_config,
                                                   char **out);

/**
 * Stream a response with explicit history. Does not modify the history.
 *
 * The counterpart to `kjarni_chat_send_with_history`. `IChatClient` and other
 * stateless APIs hand back the whole transcript on every call, so streaming has
 * to accept a history the same way sending does; without this, a streaming
 * caller could only ever produce single-turn replies.
 *
 * Roles follow the same encoding as `kjarni_chat_send_with_history`:
 * 0 = system, 1 = user, 2 = assistant.
 */
enum KjarniErrorCode kjarni_chat_stream_with_history(struct KjarniChat *chat,
                                                     const int32_t *roles,
                                                     const char *const *contents,
                                                     uintptr_t history_len,
                                                     const char *message,
                                                     const struct KjarniGenerationConfig *gen_config,
                                                     KjarniStreamCallbackFn callback,
                                                     void *user_data,
                                                     const struct KjarniCancelToken *cancel_token);

/**
 * Create a new stateful conversation from a Chat instance
 */
enum KjarniErrorCode kjarni_chat_conversation_new(struct KjarniChat *chat,
                                                  struct KjarniChatConversation **out);

/**
 * Free a ChatConversation.
 */
void kjarni_chat_conversation_free(struct KjarniChatConversation *convo);

/**
 * Send a message in a conversation and get the response
 */
enum KjarniErrorCode kjarni_chat_conversation_send(struct KjarniChatConversation *convo,
                                                   const char *message,
                                                   const struct KjarniGenerationConfig *gen_config,
                                                   char **out);

/**
 * Stream a response in a conversation.
 *
 * The user message is added to history before streaming.
 * After streaming completes, the full response is added to history.
 *
 * # Safety
 * - Same requirements as `kjarni_chat_stream`
 * - Parent Chat must still be alive
 */
enum KjarniErrorCode kjarni_chat_conversation_stream(struct KjarniChatConversation *convo,
                                                     const char *message,
                                                     const struct KjarniGenerationConfig *gen_config,
                                                     KjarniStreamCallbackFn callback,
                                                     void *user_data,
                                                     const struct KjarniCancelToken *cancel_token);

/**
 * Get the number of messages in the conversation history.
 */
uintptr_t kjarni_chat_conversation_len(const struct KjarniChatConversation *convo);

/**
 * Clear the conversation history.
 *
 * If `keep_system` is non-zero, the system prompt is preserved.
 */
void kjarni_chat_conversation_clear(struct KjarniChatConversation *convo, int32_t keep_system);

/**
 * Get the model name. Returns number of bytes written (excluding null).
 *
 * If `buf` is NULL or `buf_len` is 0, returns the required buffer size.
 */
uintptr_t kjarni_chat_model_name(const struct KjarniChat *chat, char *buf, uintptr_t buf_len);

/**
 * Get the context window size.
 */
uintptr_t kjarni_chat_context_size(const struct KjarniChat *chat);

/**
 * # Safety
 *
 * - `results` must be a value returned by `kjarni_classifier_classify`, passed here exactly
 *   once. Its buffers are invalid to read afterwards.
 */
void kjarni_class_results_free(struct KjarniClassResults results);

/**
 * Get default classifier configuration.
 */
struct KjarniClassifierConfig kjarni_classifier_config_default(void);

/**
 * Create a new Classifier.
 *
 * # Safety
 * - `config` must be valid or NULL
 * - `out` must be a valid pointer
 * - The returned handle must be freed with `kjarni_classifier_free`
 */
enum KjarniErrorCode kjarni_classifier_new(const struct KjarniClassifierConfig *config,
                                           struct KjarniClassifier **out);

/**
 * Free a Classifier.
 *
 * # Safety
 *
 * - `classifier` must be null, or a handle returned by `kjarni_classifier_new` that has not
 *   already been passed to this function. It is invalid to use afterwards.
 */
void kjarni_classifier_free(struct KjarniClassifier *classifier);

/**
 * Classify a single text.
 *
 * # Safety
 *
 * - `classifier` must be null, or a live handle returned by `kjarni_classifier_new` that has
 *   not been freed.
 * - `text` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `KjarniClassResults`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_classifier_classify(struct KjarniClassifier *classifier,
                                                const char *text,
                                                struct KjarniClassResults *out);

/**
 * Get the classifier's labels.
 *
 * # Safety
 *
 * - `classifier` must be null, or a live handle returned by `kjarni_classifier_new` that has
 *   not been freed.
 * - `out` must be a valid, writable pointer to a `KjarniStringArray`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_classifier_labels(const struct KjarniClassifier *classifier,
                                              struct KjarniStringArray *out);

/**
 * Get number of labels.
 *
 * # Safety
 *
 * - `classifier` must be null, or a live handle returned by `kjarni_classifier_new` that has
 *   not been freed.
 */
uintptr_t kjarni_classifier_num_labels(const struct KjarniClassifier *classifier);

/**
 * Get default embedder configuration.
 */
struct KjarniEmbedderConfig kjarni_embedder_config_default(void);

/**
 * Create a new Embedder.
 *
 * # Safety
 *
 * - `out` must be null, or a live handle returned by `kjarni_embedder_new` that has not been
 *   freed.
 */
enum KjarniErrorCode kjarni_embedder_new(const struct KjarniEmbedderConfig *config,
                                         struct KjarniEmbedder **out);

/**
 * Free an Embedder instance.
 *
 * # Safety
 *
 * - `embedder` must be null, or a handle returned by `kjarni_embedder_new` that has not
 *   already been passed to this function. It is invalid to use afterwards.
 */
void kjarni_embedder_free(struct KjarniEmbedder *embedder);

/**
 * Encode a single text to an embedding vector.
 *
 * # Safety
 *
 * - `embedder` must be null, or a live handle returned by `kjarni_embedder_new` that has not
 *   been freed.
 * - `text` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `KjarniFloatArray`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_embedder_encode(struct KjarniEmbedder *embedder,
                                            const char *text,
                                            struct KjarniFloatArray *out);

/**
 * Encode multiple texts to embedding vectors.
 *
 * # Safety
 *
 * - `embedder` must be null, or a live handle returned by `kjarni_embedder_new` that has not
 *   been freed.
 * - `texts` must point to `num_texts` readable pointers, each null or a valid nul-terminated
 *   C string that stays valid for the call.
 * - `out` must be a valid, writable pointer to a `KjarniFloat2DArray`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_embedder_encode_batch(struct KjarniEmbedder *embedder,
                                                  const char *const *texts,
                                                  uintptr_t num_texts,
                                                  struct KjarniFloat2DArray *out);

/**
 * Compute cosine similarity between two texts.
 *
 * # Safety
 *
 * - `embedder` must be null, or a live handle returned by `kjarni_embedder_new` that has not
 *   been freed.
 * - `text1` must be null, or a valid pointer to a nul-terminated C string.
 * - `text2` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `c_float`. It is written on both success and
 *   failure, and any buffers it receives are owned by the caller.
 */
enum KjarniErrorCode kjarni_embedder_similarity(struct KjarniEmbedder *embedder,
                                                const char *text1,
                                                const char *text2,
                                                float *out);

/**
 * Get the embedding dimension.
 *
 * # Safety
 *
 * - `embedder` must be null, or a live handle returned by `kjarni_embedder_new` that has not
 *   been freed.
 */
uintptr_t kjarni_embedder_dim(const struct KjarniEmbedder *embedder);

const char *kjarni_error_code_to_string(enum KjarniErrorCode err);

/**
 * Get the name of an error code as a C string.
 */
const char *kjarni_error_name(enum KjarniErrorCode err);

/**
 * Get the last error message. Returns NULL if no error.
 */
const char *kjarni_last_error_message(void);

/**
 * Clear the last error.
 */
void kjarni_clear_error(void);

/**
 * Free memory allocated for index info strings
 *
 * # Safety
 *
 * - `info` must be a value returned by `kjarni_index_info`, passed here exactly once. Its
 *   buffers are invalid to read afterwards.
 */
void kjarni_index_info_free(struct KjarniIndexInfo info);

/**
 * Get default indexer configuration
 */
struct KjarniIndexerConfig kjarni_indexer_config_default(void);

/**
 * Create a new Indexer
 *
 * # Safety
 *
 * - `out` must be null, or a live handle returned by `kjarni_indexer_new` that has not been
 *   freed.
 */
enum KjarniErrorCode kjarni_indexer_new(const struct KjarniIndexerConfig *config,
                                        struct KjarniIndexer **out);

/**
 * Free an Indexer handle
 *
 * # Safety
 *
 * - `indexer` must be null, or a handle returned by `kjarni_indexer_new` that has not already
 *   been passed to this function. It is invalid to use afterwards.
 */
void kjarni_indexer_free(struct KjarniIndexer *indexer);

/**
 * Create a new index from files/directories
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `inputs` must point to `the accompanying count` readable pointers, each null or a valid
 *   nul-terminated C string that stays valid for the call.
 * - `out` must be a valid, writable pointer to a `KjarniIndexStats`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_indexer_create(struct KjarniIndexer *indexer,
                                           const char *index_path,
                                           const char *const *inputs,
                                           uintptr_t num_inputs,
                                           int32_t force,
                                           struct KjarniIndexStats *out);

/**
 * Create a new index with progress callback and cancellation support.
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `inputs` must point to `the accompanying count` readable pointers, each null or a valid
 *   nul-terminated C string that stays valid for the call.
 * - `user_data` must be a valid, writable pointer to a `c_void`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 * - `cancel_token` must be null, or a live handle returned by `kjarni_cancel_token_new` that
 *   has not been freed.
 * - `out` must be a valid, writable pointer to a `KjarniIndexStats`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_indexer_create_with_callback(struct KjarniIndexer *indexer,
                                                         const char *index_path,
                                                         const char *const *inputs,
                                                         uintptr_t num_inputs,
                                                         int32_t force,
                                                         KjarniProgressCallbackFn progress_callback,
                                                         void *user_data,
                                                         const struct KjarniCancelToken *cancel_token,
                                                         struct KjarniIndexStats *out);

/**
 * Add documents to an existing index
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `inputs` must point to `the accompanying count` readable pointers, each null or a valid
 *   nul-terminated C string that stays valid for the call.
 * - `documents_added` must be a valid, writable pointer to a `usize`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_indexer_add(struct KjarniIndexer *indexer,
                                        const char *index_path,
                                        const char *const *inputs,
                                        uintptr_t num_inputs,
                                        uintptr_t *documents_added);

/**
 * Add documents to an existing index with progress callback and cancellation support.
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `inputs` must point to `the accompanying count` readable pointers, each null or a valid
 *   nul-terminated C string that stays valid for the call.
 * - `user_data` must be a valid, writable pointer to a `c_void`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 * - `cancel_token` must be null, or a live handle returned by `kjarni_cancel_token_new` that
 *   has not been freed.
 * - `documents_added` must be a valid, writable pointer to a `usize`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_indexer_add_with_callback(struct KjarniIndexer *indexer,
                                                      const char *index_path,
                                                      const char *const *inputs,
                                                      uintptr_t num_inputs,
                                                      KjarniProgressCallbackFn progress_callback,
                                                      void *user_data,
                                                      const struct KjarniCancelToken *cancel_token,
                                                      uintptr_t *documents_added);

/**
 * Get information about an existing index
 *
 * # Safety
 *
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `KjarniIndexInfo`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_index_info(const char *index_path, struct KjarniIndexInfo *out);

/**
 * Delete an index.
 *
 * # Safety
 *
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 */
enum KjarniErrorCode kjarni_index_delete(const char *index_path);

/**
 * Get the embedding model name used by the indexer.
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 * - `buf` must be null, or point to at least `buf_len` writable bytes. When it is null the
 *   required size is returned and nothing is written.
 */
uintptr_t kjarni_indexer_model_name(const struct KjarniIndexer *indexer,
                                    char *buf,
                                    uintptr_t buf_len);

/**
 * Get the embedding dimension used by the indexer.
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 */
uintptr_t kjarni_indexer_dimension(const struct KjarniIndexer *indexer);

/**
 * Get the chunk size configured for the indexer.
 *
 * # Safety
 *
 * - `indexer` must be null, or a live handle returned by `kjarni_indexer_new` that has not
 *   been freed.
 */
uintptr_t kjarni_indexer_chunk_size(const struct KjarniIndexer *indexer);

/**
 * Free rerank results
 *
 * # Safety
 *
 * - `results` must be a value returned by a rerank call, passed here exactly once. Its
 *   buffers are invalid to read afterwards.
 */
void kjarni_rerank_results_free(struct KjarniRerankResults results);

/**
 * Get default reranker configuration
 */
struct KjarniRerankerConfig kjarni_reranker_config_default(void);

/**
 * Create a new Reranker
 *
 * # Safety
 *
 * - `out` must be null, or a live handle returned by `kjarni_reranker_new` that has not been
 *   freed.
 */
enum KjarniErrorCode kjarni_reranker_new(const struct KjarniRerankerConfig *config,
                                         struct KjarniReranker **out);

/**
 * Free a Reranker
 *
 * # Safety
 *
 * - `reranker` must be null, or a handle returned by `kjarni_reranker_new` that has not
 *   already been passed to this function. It is invalid to use afterwards.
 */
void kjarni_reranker_free(struct KjarniReranker *reranker);

/**
 * Score a single query-document pair
 *
 * # Safety
 *
 * - `reranker` must be null, or a live handle returned by `kjarni_reranker_new` that has not
 *   been freed.
 * - `query` must be null, or a valid pointer to a nul-terminated C string.
 * - `document` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `c_float`. It is written on both success and
 *   failure, and any buffers it receives are owned by the caller.
 */
enum KjarniErrorCode kjarni_reranker_score(struct KjarniReranker *reranker,
                                           const char *query,
                                           const char *document,
                                           float *out);

/**
 * Rerank documents by relevance to query
 *
 * # Safety
 *
 * - `reranker` must be null, or a live handle returned by `kjarni_reranker_new` that has not
 *   been freed.
 * - `query` must be null, or a valid pointer to a nul-terminated C string.
 * - `documents` must point to `num_docs` readable pointers, each null or a valid
 *   nul-terminated C string that stays valid for the call.
 * - `out` must be a valid, writable pointer to a `KjarniRerankResults`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_reranker_rerank(struct KjarniReranker *reranker,
                                            const char *query,
                                            const char *const *documents,
                                            uintptr_t num_docs,
                                            struct KjarniRerankResults *out);

/**
 * Rerank and return top-k results
 *
 * # Safety
 *
 * - `reranker` must be null, or a live handle returned by `kjarni_reranker_new` that has not
 *   been freed.
 * - `query` must be null, or a valid pointer to a nul-terminated C string.
 * - `documents` must point to `num_docs` readable pointers, each null or a valid
 *   nul-terminated C string that stays valid for the call.
 * - `out` must be a valid, writable pointer to a `KjarniRerankResults`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_reranker_rerank_top_k(struct KjarniReranker *reranker,
                                                  const char *query,
                                                  const char *const *documents,
                                                  uintptr_t num_docs,
                                                  uintptr_t top_k,
                                                  struct KjarniRerankResults *out);

/**
 * # Safety
 * Must only be called once per `KjarniSearchResults` returned from search functions.
 */
void kjarni_search_results_free(struct KjarniSearchResults results);

struct KjarniSearchOptions kjarni_search_options_default(void);

struct KjarniSearcherConfig kjarni_searcher_config_default(void);

/**
 * - The returned handle must be freed with `kjarni_searcher_free`
 *
 * # Safety
 *
 * - `out` must be null, or a live handle returned by `kjarni_searcher_new` that has not been
 *   freed.
 */
enum KjarniErrorCode kjarni_searcher_new(const struct KjarniSearcherConfig *config,
                                         struct KjarniSearcher **out);

/**
 * # Safety
 *
 * - `searcher` must be null, or a handle returned by `kjarni_searcher_new` that has not
 *   already been passed to this function. It is invalid to use afterwards.
 */
void kjarni_searcher_free(struct KjarniSearcher *searcher);

/**
 * All pointers must be valid. Results must be freed with `kjarni_search_results_free`.
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `query` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `KjarniSearchResults`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_searcher_search(struct KjarniSearcher *searcher,
                                            const char *index_path,
                                            const char *query,
                                            struct KjarniSearchResults *out);

/**
 * All pointers must be valid. Results must be freed with `kjarni_search_results_free`.
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `query` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `KjarniSearchResults`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_searcher_search_with_options(struct KjarniSearcher *searcher,
                                                         const char *index_path,
                                                         const char *query,
                                                         const struct KjarniSearchOptions *options,
                                                         struct KjarniSearchResults *out);

/**
 * All pointers must be valid. Results must be freed with `kjarni_search_results_free`.
 *
 * # Safety
 *
 * - `index_path` must be null, or a valid pointer to a nul-terminated C string.
 * - `query` must be null, or a valid pointer to a nul-terminated C string.
 * - `out` must be a valid, writable pointer to a `KjarniSearchResults`. On `KJARNI_OK` it
 *   receives a value the caller owns and must release with the matching `*_free`; on
 *   failure it is either cleared or left unmodified, and must not be read.
 */
enum KjarniErrorCode kjarni_search_keywords(const char *index_path,
                                            const char *query,
                                            uintptr_t top_k,
                                            struct KjarniSearchResults *out);

/**
 * `searcher` must be a valid handle or null.
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 */
bool kjarni_searcher_has_reranker(const struct KjarniSearcher *searcher);

/**
 * `searcher` must be a valid handle or null.
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 */
enum KjarniSearchMode kjarni_searcher_default_mode(const struct KjarniSearcher *searcher);

/**
 * `searcher` must be a valid handle or null.
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 */
uintptr_t kjarni_searcher_default_top_k(const struct KjarniSearcher *searcher);

/**
 * Get searcher model name into caller-provided buffer
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 * - `buf` must be null, or point to at least `buf_len` writable bytes. When it is null the
 *   required size is returned and nothing is written.
 */
uintptr_t kjarni_searcher_model_name(const struct KjarniSearcher *searcher,
                                     char *buf,
                                     uintptr_t buf_len);

/**
 * Get reranker model name into caller-provided buffer
 *
 * # Safety
 *
 * - `searcher` must be null, or a live handle returned by `kjarni_searcher_new` that has not
 *   been freed.
 * - `buf` must be null, or point to at least `buf_len` writable bytes. When it is null the
 *   required size is returned and nothing is written.
 */
uintptr_t kjarni_searcher_reranker_model(const struct KjarniSearcher *searcher,
                                         char *buf,
                                         uintptr_t buf_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KJARNI_FFI_H */
